# pandas

pandas is an open sourse bsd licensed library providing high performanace easy to used data struture and data analysis tools for the python programming language

In [1]:
import pandas as pd 
import numpy as np

In [2]:
#playing with the data frame
df=pd.DataFrame(np.arange(0,20).reshape(5,4),
                index=['row1','row2','row3','row4','row5'],
                columns=['col1','col2','col3','col4'])

In [3]:
df.head()

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [4]:
df.to_csv('my_first_csv_file.csv')

In [5]:
#accesing the  elements 
## 1.. LOC 2..iLOC

In [6]:
df.loc['row1']

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int64

In [7]:
type(df.loc['row1'])

pandas.core.series.Series

In [8]:
df.iloc[:,:]

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [9]:
df.iloc[0:3,0:2]

      col1  col2
row1     0     1
row2     4     5
row3     8     9

In [10]:
type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

In [11]:
#take the element from the column 2 
df.iloc[:,1:]

      col2  col3  col4
row1     1     2     3
row2     5     6     7
row3     9    10    11
row4    13    14    15
row5    17    18    19

In [12]:
#convert dataframe into array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [13]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [14]:
df

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [15]:
df['col1'].value_counts()

col1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [16]:
df['col1'].unique()

array([ 0,  4,  8, 12, 16])