# column transforemer

In [2]:
import numpy as np 
import pandas as pd

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [6]:
df=pd.read_csv('covid_toy.csv')

In [7]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df.shape

(100, 6)

In [10]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [15]:
X_train

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
10   75  Female    NaN    Mild      Delhi
35   82  Female  102.0  Strong  Bangalore
55   81  Female  101.0    Mild     Mumbai
24   13  Female  100.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
70   68  Female  101.0  Strong      Delhi
86   25    Male  104.0    Mild  Bangalore
61   81  Female   98.0  Strong     Mumbai
53   83    Male   98.0    Mild      Delhi
93   27    Male  100.0    Mild    Kolkata

[80 rows x 5 columns]

In [21]:
 # adding simple imputer to fill the missing values in the fever column 
 si=SimpleImputer()
 X_train_fever=si.fit_transform(X_train[['fever']])
 
 # also the test data

 X_test_fever=si.transform(X_test[['fever']])
 
 X_train_fever.shape

(80, 1)

In [24]:
# ordinal encoding the cough column
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
# also the test data 
X_test_cough=oe.transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [29]:
# one hot encoder ---> gender ,city
ohe=OneHotEncoder(drop='first')

x_train_gender_city=ohe.fit_transform(X_train[['gender','city']]).toarray()

# also the test data
X_test_gender_city=ohe.transform(X_test[['gender','city']]).toarray()

x_train_gender_city.shape

(80, 4)

In [30]:
# extracting the age
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values

#also the test data
X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [31]:
x_train_transformed=np.concatenate([X_train_age,X_train_fever,X_train_cough,x_train_gender_city],axis=1)
# also the test data

X_test_transformed=np.concatenate([X_test_age,X_test_fever,X_test_cough,X_test_gender_city],axis=1)

In [33]:
x_train_transformed.shape

(80, 7)

In [34]:
x_train_transformed

array([[ 60.        , 103.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 75.        , 100.83098592,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 82.        , 102.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 81.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 13.        , 100.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 23.        ,  98.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 27.        , 100.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ],
       [ 83.        , 103.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 16.        , 104.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 82.        , 100.83098592,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 55.        , 100.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 20.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 50.        , 103.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 66.        ,  99.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 42.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 23.        , 100.83098592,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 34.        , 104.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 12.        ,  98.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 44.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 59.        ,  99.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 47.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 33.        , 102.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 73.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 65.        ,  99.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ],
       [ 34.        , 100.83098592,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 71.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 42.        , 101.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ],
       [ 51.        , 104.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 74.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 51.        , 101.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 12.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 24.        , 102.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 65.        ,  99.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 11.        , 100.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 19.        , 101.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ],
       [ 14.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 60.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 16.        , 103.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 80.        , 100.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 71.        , 100.83098592,   1.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 27.        , 100.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ],
       [ 38.        , 100.83098592,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ],
       [ 79.        , 100.83098592,   1.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 19.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 11.        , 100.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 64.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 22.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 40.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 46.        , 103.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [  5.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 25.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 80.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 56.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 17.        , 104.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 54.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 64.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 49.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 69.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 38.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 51.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 83.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 10.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [  6.        , 104.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 26.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 34.        ,  98.        ,   1.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 24.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [  5.        , 102.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 42.        , 100.83098592,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 20.        , 100.83098592,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 49.        , 102.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 47.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 68.        , 101.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 25.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 81.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 83.        ,  98.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ]])

In [41]:
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[('tnf1',SimpleImputer(),['fever']),
                                            ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                            ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])],remainder='passthrough')

In [42]:
transformer.fit_transform(X_train)

array([[103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [100.83098592,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  82.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  13.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [100.83098592,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  55.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  69.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  50.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [100.83098592,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  44.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  59.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [ 99.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  65.        ],
       [100.83098592,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  74.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  24.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  11.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  19.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  60.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  16.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [100.83098592,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [100.83098592,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  38.        ],
       [100.83098592,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  79.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  40.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  46.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  17.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  69.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  38.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  51.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   6.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  26.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  24.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [100.83098592,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [100.83098592,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  68.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ]])